#!/bin/bash

# make sure a valid day is provided
if [ $# -eq 0 ]; then
    echo "provide a day as an argument"
    exit 1
elif ! [[ $1 =~ ^-?[0-9]+$ ]]; then
    echo "provide a valid day"
elif [ $1 -le 0 ] || [ $1 -gt 25 ]; then
    echo "provide a day between 1-25"
fi

DID_SOMETHING=0

DAY=$1

# create file for solving the problem
SOLN_FILE="solns/day$DAY.py"

if [ ! -f "$SOLN_FILE" ]; then
    echo "creating" $SOLN_FILE
    cp solns/template.py $SOLN_FILE
    DID_SOMETHING=1
fi


# download input if not found
INPUT_FILE="solns/$DAY.in"

if [ ! -f $INPUT_FILE ]; then
    python3 aoc_input.py $DAY
    DID_SOMETHING=1
fi


# print final message if nothing happened
if [ $DID_SOMETHING -eq 0 ]; then
    echo "nothing to be done..."
fi





