#!/bin/bash

# make sure a valid day is provided
if [ $# -eq 0 ]; then
    echo "provide a day as an argument"
    exit 1
elif ! [[ $1 =~ ^-?[0-9]+$ ]]; then
    echo "provide a valid day"
    exit 1
elif [ $1 -le 0 ] || [ $1 -gt 25 ]; then
    echo "provide a day between 1-25"
    exit 1
fi

DAY=$1

# create file for solving the problem
SRC_FILE="src/day$DAY.py"

if [ ! -f "$SRC_FILE" ]; then
    echo "couldn't find solutionn file: $SRC_FILE"
    exit 1
fi


# download input if not found
INPUT_FILE="src/$DAY.in"

if [ ! -f $INPUT_FILE ]; then
    echo "couldn't find input file: $INPUT_FILE"
fi

python3 $SRC_FILE



